services:
  postgres:
    image: postgres:16
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"  
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_backups:/backups
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    security_opt:
      - no-new-privileges:true

  pgadmin:
    image: dpage/pgadmin4:9
    container_name: pgadmin
    restart: always
  
    ports:
      - "127.0.0.1:8080:80" # Accessible solo desde el host
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - backend
    depends_on:
      - postgres
    security_opt:
      - no-new-privileges:true

volumes:
  postgres_data:
  pgadmin_data:
  postgres_backups:
    driver: local
    driver_opts:
      type: none
      device: ./backups
      o: bind

networks:
  backend:
    driver: bridge
