version: '3.8'

services:
  sveltekit-app:
    image: registry.codlec.com/appkit
    container_name: appkit-codlec
    ports:
      - "127.0.0.1:3000:3000" # Puerto local 3000
    restart: always
    environment:
      PG_CONNECTION_STR: ${PG_CONNECTION_STR}
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      GEMINI_MODEL: ${GEMINI_MODEL}
      SECRET_SESSION_HASH: ${SECRET_SESSION_HASH}
      SESSION_COOKIE_TOKEN_NAME: ${SESSION_COOKIE_TOKEN_NAME}
      NODE_ENV: ${NODE_ENV:-development}
      SEQ_SERVER_URL: ${SEQ_SERVER_URL}
      ORIGIN: ${ORIGIN:-http://127.0.0.1:3000}
    networks:
      - backend 

networks:
  backend:
    driver: bridge

